fix: events no longer grows-while-looping anymore
stevearc/profile.nvim pull request #7
Opened 2024-11-06 03:54 UTC by ColinKennedy

Closes https://github.com/stevearc/profile.nvim/issues/6

The issue was that `events` was growing in-size while the for loop was running. By making a shallow copy here, the loop completes as expected.

2024-11-06 17:48 UTC, stevearc requested changes
Sounds like this is because the `export` is called while profiling is still ongoing. What do you think about a solution that either pauses profiling during the `export` call or just stops it altogether at the beginning of `export`?

2024-11-06 18:48 UTC, ColinKennedy commented
> What do you think about a solution that either pauses profiling during the export

Do you mean I should pause on the caller-side before exporting? Or did you mean "we could call pause within the `export()`  function"? I'm happy to do either, just wanted to clarify which you're suggesting.

2024-11-06 20:49 UTC, stevearc commented
Like we could set `instrument.recording = false` at the top of `export` and restore the previous value at the bottom

2024-11-08 21:14 UTC, ColinKennedy commented
Okay cool, that's what you thought you meant. I pushed the change just now

2024-11-09 05:00 UTC, stevearc commented
LGTM thanks for the PR!

2024-11-09 05:01 UTC, merged