Added get_process_id / get_thread_id
stevearc/profile.nvim pull request #8
Opened 2024-12-29 22:05 UTC by ColinKennedy

I noticed that the `pid` and `tid` values that this plugin writes out seem to just be placeholders. I've added implementations for the events that have been working for me and wanted to contribute them back.

2025-01-03 20:47 UTC, stevearc requested changes
Appreciate it! One request

2025-01-03 20:47 UTC, stevearc commented on lua/profile/util.lua
> +      ]])
Could we move the cdefs outside of the function call? Or make it a once-only call? Running the C parser for every single event will bog us down a lot and skew the results.

2025-01-03 20:57 UTC, ColinKennedy commented on lua/profile/util.lua
> +      ]])
You're right my bad. I'll make it once-only at best and if not make it global so it isn't calling each time the function runs

2025-01-04 15:03 UTC, ColinKennedy commented on lua/profile/util.lua
> +      ]])
I thought about it and if you don't mind let's do a global definition instead. A run-once makes sense in a situation where there's a good chance the function isn't called but since it's part of the main profiler it's going to be called pretty much for sure. We might as well skip the run-once overhead.

2025-01-04 17:25 UTC, stevearc commented on lua/profile/util.lua
> +      ]])
Yep, I agree this is simpler and doesn't have much downside

2025-01-04 17:25 UTC, stevearc commented
Thanks for the PR!

2025-01-04 17:26 UTC, merged