Added events as an optional export parameter
stevearc/profile.nvim pull request #9
Opened 2024-12-30 00:38 UTC by ColinKennedy

This PR modifies the export process.

Before: Export the global `instrument.get_events()`
After: If the user has provided an explicit list of events, export those. Otherwise, export the global `instrument.get_events()`

Sometimes I want to export a subset of the overall events. So I make a copy using `vim.fn.copy(instrument.get_events())`, get a slice of those events, and now just need a way to export that slice. This PR makes that possible.

2025-01-03 21:23 UTC, stevearc requested changes
If you're only interested in a subset of the events, it would be better if we can avoid creating them in the first place. Is there some sort of filtering or targeting feature we could add to only record the events you're interested in?

If that is infeasible and you still want to do it this way, I'd actually prefer separating out the function to export a list of events into a separate, non-public (or at least non-publicly-documented) function. The reason is that I think this is a pretty niche use case and not something I would encourage users to do with this plugin, so I'd prefer to keep it out of the public API.

2025-01-03 21:40 UTC, ColinKennedy commented
I'll describe my use-case a bit more.

I'm creating a tool that can track "best case" runs of Neovim plugins / startup etc. profile.nvim is the backend.

The basic logic is like this:

- set a counter to 10

in a while loop...
- start profiling (which also clears any previous events)
- Do X (run unittests, do Neovim startup, etc)
- record all profiler events
- if faster than the last run...
    - set counter to 10
    - copy / keep track of the profiler events
- decrement the counter by 1
- once counter hits zero, the while loop ends
- export the events from the best / fastest run

The end effect is that the run that is the fastest of 10 runs is considered the "best / fastest" and I use the profile results from that. Currently I'm accomplishing this by copying instruction.get_events() and then exporting those events at the end. If I didn't do this then one of the earlier, slower runs would contaminate the results of the run that I actually did want.

So to clarify I'm not looking to keep a subset of the events (although that could be its own use-case). I'm keeping track of a snapshot of events, keeping each separate from each other, and then exporting the best one.

My plan is to eventually make this into a really easy to use, one-liner GitHub workflow that anyone can add to their plugins. At the rate I'm going it'll be a couple months before it's ready to show.

2025-01-04 00:18 UTC, stevearc commented
Thanks for explaining, the use case makes sense now. In that case, I think the second option I suggested makes sense. You can create a new method like `M.write_events_to_file` and throw a `---@private` in the docstring to keep it out of the public API, and the existing `M.export` function can call it.

2025-01-04 21:02 UTC, stevearc commented
LGTM thanks!

2025-01-04 21:02 UTC, merged